//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFSTFServiceHook.TFSTFServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TFSTFServices.ITFSMessageService")]
    internal interface ITFSMessageService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITFSMessageService/NewWorkItemMessage")]
        void NewWorkItemMessage(string messageData);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITFSMessageService/NewWorkItemMessage")]
        System.Threading.Tasks.Task NewWorkItemMessageAsync(string messageData);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITFSMessageService/NewGitPushMessage")]
        void NewGitPushMessage(string messageData);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITFSMessageService/NewGitPushMessage")]
        System.Threading.Tasks.Task NewGitPushMessageAsync(string messageData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface ITFSMessageServiceChannel : TFSTFServiceHook.TFSTFServices.ITFSMessageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class TFSMessageServiceClient : System.ServiceModel.ClientBase<TFSTFServiceHook.TFSTFServices.ITFSMessageService>, TFSTFServiceHook.TFSTFServices.ITFSMessageService {
        
        public TFSMessageServiceClient() {
        }
        
        public TFSMessageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TFSMessageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TFSMessageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TFSMessageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void NewWorkItemMessage(string messageData) {
            base.Channel.NewWorkItemMessage(messageData);
        }
        
        public System.Threading.Tasks.Task NewWorkItemMessageAsync(string messageData) {
            return base.Channel.NewWorkItemMessageAsync(messageData);
        }
        
        public void NewGitPushMessage(string messageData) {
            base.Channel.NewGitPushMessage(messageData);
        }
        
        public System.Threading.Tasks.Task NewGitPushMessageAsync(string messageData) {
            return base.Channel.NewGitPushMessageAsync(messageData);
        }
    }
}
